M = int(input())
N = 1000-M
i = N//100
j = (N - (i*100))//10
k = N % 10
count = 0

if(i >=5 ):
    a = N //500
    N-=(500*a)
    count += a
    a_num = N//100
    N -=(100*a_num)
    count+= a_num
elif(i>=0):
    b = N // 100
    N-=(100*b)
    count += b
if(j >= 5):
    c = N //50
    N-=(50*c)
    count += c
    c_num = N // 10
    N-=(10*c_num)
    count += c_num
elif(j>=0):
    d = N // 10
    N-=(10*d)
    count += d
if(k >=5):
    e = N//5
    N-=(5*e)
    count += e
    e_num = N//1
    N-=(1*e_num)
    count+=e_num
elif(k>=0):
    f = N //1
    N -= (1*f)
    count += f
print(count)